name: PR Deployment CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: windows-latest
    environment:
      name: 'PR-slot-deployment'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 'b6ddf09a-d1ae-41d9-ab17-27f0c9d0007e'
          client-secret: 'COG8Q~myBR33J3BXJYw7u3OhkSOvzAFs_NlRYcXi'
          tenant-id: '960eb600-b7c2-4578-951f-16b91d9a10c7'
          subscription-id: '8e56a151-a6a5-4c15-94fc-20459cc65f3b'

      - name: Create Deployment Slot
        run: |
          $SLOT_NAME="pr-${{ github.event.number }}"
          az webapp deployment slot create --name prdeploymentwebapp --resource-group prdeployment --slot $SLOT_NAME
          
  cleanup:
    if: github.event.action == 'closed'
    runs-on: windows-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 'b6ddf09a-d1ae-41d9-ab17-27f0c9d0007e'
          client-secret: 'COG8Q~myBR33J3BXJYw7u3OhkSOvzAFs_NlRYcXi'
          tenant-id: '960eb600-b7c2-4578-951f-16b91d9a10c7'
          subscription-id: '8e56a151-a6a5-4c15-94fc-20459cc65f3b'

      - name: Delete Deployment Slot
        run: |
          $SLOT_NAME="pr-${{ github.event.number }}"
          az webapp deployment slot delete --name prdeploymentwebapp --resource-group prdeployment --slot $SLOT_NAME --no-wait
