name: PR Deployment CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    if: github.event.action != 'closed'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build src/WebApplication/WebApplication.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/WebApplication/WebApplication.csproj -c Release -o ./deploy

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./deploy

  deploy:
    if: github.event.action != 'closed'
    runs-on: windows-latest
    needs: build
    environment:
      name: 'PR-slot-deployment'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 'b6ddf09a-d1ae-41d9-ab17-27f0c9d0007e'
          client-secret: 'COG8Q~myBR33J3BXJYw7u3OhkSOvzAFs_NlRYcXi'
          tenant-id: '960eb600-b7c2-4578-951f-16b91d9a10c7'
          subscription-id: '8e56a151-a6a5-4c15-94fc-20459cc65f3b'

      - name: Create Deployment Slot
        run: |
          $SLOT_NAME="pr-${{ github.event.number }}"
          az webapp deployment slot create --name prdeploymentwebapp --resource-group prdeployment --slot $SLOT_NAME
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prdeploymentwebapp'
          slot-name: 'pr-${{ github.event.number }}'
          package: './deploy'
          
  cleanup:
    if: github.event.action == 'closed'
    runs-on: windows-latest
    environment:
      name: 'PR-slot-deployment'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 'b6ddf09a-d1ae-41d9-ab17-27f0c9d0007e'
          client-secret: 'COG8Q~myBR33J3BXJYw7u3OhkSOvzAFs_NlRYcXi'
          tenant-id: '960eb600-b7c2-4578-951f-16b91d9a10c7'
          subscription-id: '8e56a151-a6a5-4c15-94fc-20459cc65f3b'

      - name: Delete Deployment Slot
        run: |
          $SLOT_NAME="pr-${{ github.event.number }}"
          az webapp deployment slot delete --name prdeploymentwebapp --resource-group prdeployment --slot $SLOT_NAME --no-wait
